provider:
  name: openfaas

functions:
  sleep:
    lang: go
    handler: ./sleep
    image: ghcr.io/${OWNER:-openfaas}/sleep:${TAG:-latest}
    environment:
      sleep_duration: 10s
      combine_output: false
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 60s

