provider:
  name: openfaas

functions:
  sleep:
    lang: go
    handler: ./sleep
    image: ghcr.io/${OWNER:-openfaas}/sleep:${TAG:-latest}
    environment:
      sleep_duration: 10s
      combine_output: false

